# Use the official PHP image as base
FROM php:8.0-fpm

# Set working directory within the container
WORKDIR /var/www/html

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    zip \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd pdo_mysql zip

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy application code into container
COPY . .

# Install PHP dependencies
RUN composer install

# Expose port 9000 to communicate with Nginx or other web servers
EXPOSE 9000

# Command to run the PHP-FPM server
CMD ["php-fpm"]
