name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/ernissmal/Ernests-Smalikis-portfolio.git .
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Setup Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Deploy
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force
